/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Tado adapter settings": {                       "en": "Tado adapter settings",                           "de": "Tado-Adaptereinstellungen",                       "ru": "Настройки адаптера Tado",                         "pt": "Configurações do adaptador Tado",                 "nl": "Tado adapter instellingen",                       "fr": "Paramètres de l'adaptateur Tado",                 "it": "Impostazioni dell'adattatore Tado",               "es": "Configuraciones del adaptador Tado",              "pl": "Ustawienia adaptera Tado",                        "zh-cn": "Tado适配器设置"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "имя пользователя",                                "pt": "Nome de usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
    "intervall": {                                   "en": "Refresh interval in seconds",                     "de": "Aktualisierungsintervall in Sekunde",             "ru": "Обновить интервал в секунду",                     "pt": "Atualizar intervalo em segundo",                  "nl": "Vernieuw intervall in seconde",                   "fr": "Rafraîchir l'intervalle en seconde",              "it": "Intervallo di aggiornamento al secondo",          "es": "Actualizar intervalo en segundo",                 "pl": "Odśwież interwał w sekundę",                      "zh-cn": "刷新间隔秒"},
    "tado adapter settings": {                       "en": "Adapter settings for tado",                       "de": "Adaptereinstellungen für tado",                   "ru": "Настройки адаптера для tado",                     "pt": "Configurações do adaptador para tado",            "nl": "Adapterinstellingen voor tado",                   "fr": "Paramètres d'adaptateur pour tado",               "it": "Impostazioni dell'adattatore per tado",           "es": "Ajustes del adaptador para tado",                 "pl": "Ustawienia adaptera dla tado",                    "zh-cn": "tado的适配器设置"},
};