/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Interval in seconds": {                         "en": "Interval in seconds",                             "de": "Intervall in Sekunden",                           "ru": "Интервал в секундах",                             "pt": "Intervalo em segundos",                           "nl": "Interval in seconden",                            "fr": "Intervalle en secondes",                          "it": "Intervallo in secondi",                           "es": "Intervalo en segundos",                           "pl": "Interwał w sekundach",                            "zh-cn": "以秒为单位的间隔"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Please provide your credentials": {             "en": "Please provide your credentials",                 "de": "Bitte geben Sie Ihre Anmeldedaten an",            "ru": "Пожалуйста, предоставьте свои учетные данные",    "pt": "Por favor, forneça suas credenciais",             "nl": "Geef uw inloggegevens op",                        "fr": "Veuillez fournir vos identifiants",               "it": "Si prega di fornire le proprie credenziali",      "es": "Por favor proporcione sus credenciales",          "pl": "Podaj swoje dane uwierzytelniające",              "zh-cn": "请提供您的凭据"},
    "Tado adapter settings": {                       "en": "Tado adapter settings",                           "de": "Tado Adaptereinstellungen",                       "ru": "Настройки адаптера Tado",                         "pt": "Configurações do adaptador Tado",                 "nl": "Tado adapter instellingen",                       "fr": "Paramètres de l'adaptateur Tado",                 "it": "Impostazioni dell'adattatore Tado",               "es": "Configuraciones del adaptador Tado",              "pl": "Ustawienia adaptera Tado",                        "zh-cn": "Tado适配器设置"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "Имя пользователя",                                "pt": "Nome de usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
    "intervall": {                                   "en": "Refresh interval in seconds",                     "de": "Aktualisierungsintervall in Sekunde",             "ru": "Обновить интервал в секунду",                     "pt": "Atualizar intervalo em segundo",                  "nl": "Vernieuw intervall in seconden",                  "fr": "Rafraîchir l'intervalle en seconde",              "it": "Intervallo di aggiornamento al secondo",          "es": "Actualizar intervalo en segundo",                 "pl": "Odśwież interwał w sekundę",                      "zh-cn": "刷新间隔（秒）"},
    "tado adapter settings": {                       "en": "Adapter settings for tado",                       "de": "Adaptereinstellungen für tado",                   "ru": "Настройки адаптера для tado",                     "pt": "Configurações do adaptador para tado",            "nl": "Adapter instellingen voor Tado",                  "fr": "Paramètres d'adaptateur pour tado",               "it": "Impostazioni dell'adattatore per tado",           "es": "Ajustes del adaptador para tado",                 "pl": "Ustawienia adaptera dla tado",                    "zh-cn": "Tado适配器设置"},
};